### ISSUE TITLE
ec-overlayRoleのfadeIn/Outについて

### ISSUE THREAD

**Issue by chihiro-adachi** [EC-CUBE/Eccube-Styleguide#154]
ec-overlayRoleに、fadeIn/Outの定義がありますが、これは必要でしょうか？

```css
.ec-overlayRole {
  ...
  -webkit-animation: fadeOut 150ms linear 0s;
          animation: fadeOut 150ms linear 0s; 
}

.have_curtain .ec-overlayRole {
  ...
  -webkit-animation: fadeIn 150ms linear 0s;
          animation: fadeIn 150ms linear 0s; }
```

CodeCeptionで自動テストを行う際に、fadeIn/Outの影響でクリックの判定を行うのが難しく、可能であればこの定義を削除できればと考えています。
